[affetto]
name = "affetto"

[[affetto.chain.link]]
name = "torso"
jointtype = "fixed"
frame = [
  [ 1, 0, 0, 0 ],
  [ 0, 1, 0, 0 ],
  [ 0, 0, 1, 0 ],
]

[[affetto.chain.link]]
name = "waist"
jointtype = "revolute"
range = []
frame = []
parent =  "torso"

[[affetto.chain.link]]
name = "left shoulder elevation"
jointtype = "revolute"
range = []
frame = []
parent = "waist"

[[affetto.chain.link]]
name = "left shoulder abduction"
jointtype = "revolute"
range = []
frame = []
parent = "left shoulder elevation"

[[affetto.chain.link]]
name = "left shoulder flextion"
jointtype = "revolute"
range = []
frame = []
parent = "left shoulder abduction"

[[affetto.chain.link]]
name = "left elbow rotation"
jointtype = "revolute"
range = []
frame = []
parent = "left shoulder flextion"

[[affetto.chain.link]]
name = "left elbow flextion"
jointtype = "revolute"
range = []
frame = []
parent = "left elbow rotation"

[[affetto.chain.link]]
name = "left wrist supination"
jointtype = "revolute"
range = []
frame = []
parent = "left elbow flextion"

[[affetto.chain.link]]
name = "left hand"
jointtype = "fixed"
range = []
frame = []
parent = "left wrist supination"

[[affetto.chain.link]]
name = "right shoulder elevation"
jointtype = "revolute"
range = []
frame = []
parent = "waist"

[[affetto.chain.link]]
name = "right shoulder abduction"
jointtype = "revolute"
range = []
frame = []
parent = "right shoulder elevation"

[[affetto.chain.link]]
name = "right shoulder flextion"
jointtype = "revolute"
range = []
frame = []
parent = "right shoulder abduction"

[[affetto.chain.link]]
name = "right elbow rotation"
jointtype = "revolute"
range = []
frame = []
parent = "right shoulder flextion"

[[affetto.chain.link]]
name = "right elbow flextion"
jointtype = "revolute"
range = []
frame = []
parent = "right elbow rotation"

[[affetto.chain.link]]
name = "right wrist supination"
jointtype = "revolute"
range = []
frame = []
parent = "right elbow flextion"

[[affetto.chain.link]]
name = "right hand"
jointtype = "fixed"
range = []
frame = []
parent = "right wrist supination"


[affetto.comm]
[affetto.comm.remote]
host = "192.168.5.10"
port = 50010

[affetto.comm.local]
host = "192.168.5.109"
port = 50000

[affetto.mock]
[affetto.mock.remote]
host = "localhost"
port = 50000

[affetto.mock.local]
host = "localhost"
port = 50010

[affetto.mock.sensor]
rate = 100

[affetto.mock.valve]
rate = 30


[affetto.state]
freq = 30


[affetto.ctrl]
scheme = "PID"
input_range = [0, 600]  # kPa

[affetto.ctrl.pid]
kP = [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5]
kD = [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02]
kI = [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
stiff = [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400]

[affetto.ctrl.pidf]
kP = [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5]
kD = [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02]
kI = [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
stiff = [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400]


[command]
# Frequency rate to send commands
rate = 30
# Time duration in total
time = 55  # [sec]

[command.profile.constant]
# Default values for constant profile
value = 0

[command.profile.sinusoidal]
# Default values for sinusoidal profile
amplitude = 127
period = 10
base = 127
idletime = 5
phase = 0

[command.affetto]
[command.affetto.9]
profile = "constant"
ca.params = { value = 175 }
cb.params = { value = 96 }

[command.affetto.11]
profile = "sinusoidal"
params = { amplitude = 127, period = 10, base = 127, idletime = 5 }
ca.params = { phase = 0 }
# cb.params = { phase = "np.pi" }
cb.profile = "constant"
cb.params = { value = 127}
